#!/bin/sh

# for now omit -Xshare:on
/opt/jre-slim/bin/java --add-opens java.base/java.util=ALL-UNNAMED -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -cp "/opt/aws-lambda-java-runtime-interface-client-2.3.1.jar:/opt/aws-lambda-java-core-1.2.2.jar:/opt/aws-lambda-java-serialization-1.1.2.jar:$LAMBDA_TASK_ROOT:$LAMBDA_TASK_ROOT/*:$LAMBDA_TASK_ROOT/lib/*:/opt/java/lib/*" com.amazonaws.services.lambda.runtime.api.client.AWSLambda "$_HANDLER"
